# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_name', models.CharField(max_length=200)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('Pincode', models.TextField()),
                ('capacity', models.IntegerField(default=100)),
                ('ratio', models.FloatField()),
            ],
        ),
    ]
