# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('locker_id', models.IntegerField(primary_key=True, serialize=False)),
                ('locker_name', models.CharField(blank=True, db_column='Locker_name', max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('pincode', models.CharField(blank=True, max_length=45, null=True)),
                ('prime_capacity', models.CharField(blank=True, max_length=45, null=True)),
                ('standard_capacity', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
