# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170321_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table1',
            options={'managed': False},
        ),
    ]
