# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170321_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('key_p', models.AutoField(primary_key=True, serialize=False)),
                ('day0', models.IntegerField(blank=True, null=True)),
                ('day1', models.IntegerField(blank=True, null=True)),
                ('day2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('key_s', models.AutoField(primary_key=True, serialize=False)),
                ('day0', models.IntegerField(blank=True, null=True)),
                ('day1', models.IntegerField(blank=True, null=True)),
                ('day2', models.IntegerField(blank=True, null=True)),
                ('day3', models.IntegerField(blank=True, null=True)),
                ('day4', models.IntegerField(blank=True, null=True)),
                ('day5', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='table1',
            options={'managed': False},
        ),
    ]
