# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170323_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prime',
            options={},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='table1',
            options={},
        ),
    ]
