# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170323_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prime',
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
